### ISSUE TITLE
Practice 2 - localizer - code comments

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#1]
Please fix the following

1. There are 2 times when the same variable name is used. One of them should be renamed, because currently when you calculate yaw  angle and assign it to `y` then later you overwrite it when calculating quaternion
   - [`y = convert_azimuth_to_yaw(math.radians(msg.azimuth-azimuth_correction))`](https://github.com/Zillaynain/autoware_mini_practice/blob/6a4f012971b1d6b8e15f3ad356279820a849dc3a/practice_2/nodes/localization/localizer.py#L43)
   - [`x, y, z, w = quaternion_from_euler(0, 0, y)`](https://github.com/Zillaynain/autoware_mini_practice/blob/6a4f012971b1d6b8e15f3ad356279820a849dc3a/practice_2/nodes/localization/localizer.py#L46)
2. Here I suggest again renaming the variables, using `origin` and `_b` is very confusing. This is not origin any more - these are actual ego vehicle locations and to transform these to map coordinates we are subtracting origin
   - [`self.origin_x_b, self.origin_y_b = self.transformer.transform(msg.latitude, msg.longitude) `](https://github.com/Zillaynain/autoware_mini_practice/blob/6a4f012971b1d6b8e15f3ad356279820a849dc3a/practice_2/nodes/localization/localizer.py#L39)
3. You can calculate it there, but I would do it before, where the other calculations are done and assign it to a variable. When creating a message I would use the variable not the calculation.
   - [`current_velocity.twist.linear.x = math.sqrt(msg.north_velocity**2 + msg.east_velocity**2)`](https://github.com/Zillaynain/autoware_mini_practice/blob/6a4f012971b1d6b8e15f3ad356279820a849dc3a/practice_2/nodes/localization/localizer.py#L61)
4. And maybe using similar style when creating variables for the messages - the second one is without `_msg`. And `current_velocity` might mean different thing in another context - Here it should be made obvious that it is a message
   - `current_pose_msg = PoseStamped()`
   - `current_velocity = TwistStamped()`
  
Code was doing what it is supposed to do - well done! Its just the variable naming currently. Try to choose as clear and self-explanatory names as possible.

**Comment by Zillaynain** [comment]
I have made the changes

**Comment by geopimik** [comment]
ok
