### ISSUE TITLE
Practice 7 - camera_traffic_light_detector

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#10]
In `local_path_callback`, you are creating a `stoplines_on_path` list, but if there are no waypoints, it will become  `None`.

https://github.com/Zillaynain/autoware_mini_practice/blob/5a3fb5548f149fbd957bacad174efd37e01fe563/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L105-L122

If it is `None`, it returns from `camera_image_callback`, and no images are published if there are no stop lines. 

https://github.com/Zillaynain/autoware_mini_practice/blob/5a3fb5548f149fbd957bacad174efd37e01fe563/practice_7/nodes/detection/tfl_camera/camera_traffic_light_detector.py#L130-L132

We wanted the images to be continuously published. So instead of assigning `None` to `stoplines_on_path` - you should publish an empty list instead.

**Comment by Zillaynain** [comment]
Please Check

**Comment by geopimik** [comment]
The amount of code should be kept minimal! Less code is easier to manage and understand. In your current change you could again trim the code shorter.

You have:
```
    def local_path_callback(self, local_path_msg):

        if len(local_path_msg.waypoints) > 0:
            # used in calculate_roi_coordinates to filter out only relevant signals
            stoplines_on_path = []

            waypoints = [(wp.pose.pose.position.x, wp.pose.pose.position.y) for wp in local_path_msg.waypoints]
            local_path = LineString(waypoints)

            for id, linestring in self.tfl_stoplines.items():
                if local_path.intersects(linestring):
                    stoplines_on_path.append(id)
        else:
            stoplines_on_path = []

        with self.lock:
            self.stoplines_on_path = stoplines_on_path
            self.transform_from_frame = local_path_msg.header.frame_id
```

You could have:

```
    def local_path_callback(self, local_path_msg):

        # used in calculate_roi_coordinates to filter out only relevant signals
        stoplines_on_path = []

        if len(local_path_msg.waypoints) > 0:
            waypoints = [(wp.pose.pose.position.x, wp.pose.pose.position.y) for wp in local_path_msg.waypoints]
            local_path = LineString(waypoints)

            for id, linestring in self.tfl_stoplines.items():
                if local_path.intersects(linestring):
                    stoplines_on_path.append(id)
  
        with self.lock:
            self.stoplines_on_path = stoplines_on_path
            self.transform_from_frame = local_path_msg.header.frame_id
```
* set `stoplines_on_path = []` outside if and else
* discard the `else` entirely

**Comment by Zillaynain** [comment]
Please check.

**Comment by geopimik** [comment]
ok
