### ISSUE TITLE
Practice_4 - lanelet2_global_planner - code comments

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#3]
#### Comments:
1. You don't need class / global variable `self.waypoints`
   - In `goal_callback` you can use just local variable `waypoints`
   - In `current_pose_callback` you can do just `self.publish_waypoints([])`, so no need for `self.waypoints = []`
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L33

2. First thing in `goal_callback` should be to check if `self.current_location` is available
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L57-L60

3. There should be a logwarn message if no route is found
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L72-L73

4. If path is cleared it is correct to clear also the goal point - enable it
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L92

5. Remove unnecessary and debugging code lines:
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L80
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L95

6. If there is `speed_ref` this will be the final speed, you should also make sure that it does not exceed `speed_limit`. And you cant put the `rospy.get_param('~speed_limit')` here. Getting parameter values should be at the beginning where the class is initialized together with other parameters.
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/planning/global/lanelet2_global_planner.py#L101-L106

**Comment by Zillaynain** [comment]
I have incorporated all the comments

**Comment by geopimik** [comment]
1-5 OK

6. Still missing the check that `speed` should never be over the`self.speed_limit`

**Comment by Zillaynain** [comment]
Please check

**Comment by geopimik** [comment]
Ok, seems to work, but the implementation has too much code for that simple thing:

You have: 
https://github.com/Zillaynain/autoware_mini_practice/blob/5a3fb5548f149fbd957bacad174efd37e01fe563/practice_4/nodes/planning/global/lanelet2_global_planner.py#L102-L110

But you could just have:
```
        speed = self.speed_limit / 3.6
        for lanelet in path_no_lane_change:
                if 'speed_ref' in lanelet.attributes:
                    speed = min(speed, float(lanelet.attributes['speed_ref'])/3.6)
```
