### ISSUE TITLE
Practice 4 - pure_pursuit_follower - code comments

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#4]
####  Comments

1. As a reminder there are some comments in the #2 that have not been updated yet
2. I the `path_callback`
   - `if len(msg.waypoints) !=0:`
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/control/pure_pursuit_follower.py#L57-L59
   - But in else only one of them
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/control/pure_pursuit_follower.py#L60-L61

3. First thing in `current_pose_callback` should be assigning `self.path_linestring` and `self.distance_to_velocity_interpolator` to local variables using `threading.lock()` and then check if they are not None and only then proceed to use them in the callback
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/control/pure_pursuit_follower.py#L64-L67

4. Why do you have unused and almost copy of the `current_pose_callback` called `**a**current_pose_callback` in your code? Delete any unnecessary code!
https://github.com/Zillaynain/autoware_mini_practice/blob/8304c8d0cc018d758cd8c7153778f83ce0af80ba/practice_4/nodes/control/pure_pursuit_follower.py#L88-L111

**Comment by Zillaynain** [comment]
all the comments incorporated.

**Comment by geopimik** [comment]
1. OK
4. OK

3. You are setting `self.path_linestring` already in if and else, same with `self.distance_to_velocity_interpolator`. In if and else you should set only local variable and global variable should be set under self.lock.

https://github.com/Zillaynain/autoware_mini_practice/blob/06c5047b05955dbe2bd7b2d8819646841408d540/practice_4/nodes/control/pure_pursuit_follower.py#L57-L65

4.  In the beginning of the `current_pose_callback` you should set path_linestring value from global variable using self.lock.

**Comment by Zillaynain** [comment]
Please check

**Comment by geopimik** [comment]
ok
