### ISSUE TITLE
Practice 5 - cluster_detector - code comments

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#6]
#### Comments

1. You should add a check somewhere at the beginning of `cluster_callback` if there are no objects (no labels), then it should straight away publish an empty detected_objects message, and there is no point in trying to get the transform and execute some other code in that callback.

2. This part should be tabulated and under the `if msg.header.frame_id != self.output_frame:`. It has a point only if transforms are not equal.
https://github.com/Zillaynain/autoware_mini_practice/blob/bedb45f21872eb96ff14be9d5aa3fa6f47e8a918/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L46-L49

3. You shouldn't need to make it here as a class variable, and using the `DetectedObject` as a variable name is also very confusing. Could use simply `object`.
https://github.com/Zillaynain/autoware_mini_practice/blob/bedb45f21872eb96ff14be9d5aa3fa6f47e8a918/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L80

**Comment by geopimik** [comment]
These seem not fixed yet!

**Comment by Zillaynain** [comment]
Please check

**Comment by geopimik** [comment]
1. This check would not work. `data['label']` won't be `None`. Instead it can be emty, so yu should check legth instead. And if there are no labels you should publish empty message and return from the callback. You are missing the return

2. ok

3. 2 things:
  - Do not use `self` - this should be used only in class init part and it refers to class variables. 
  - Capital letter refers to class name, you are creating an instance and it should be with small letter.
  - so instead what you have you should use just `object = DetectedObject(header=header)`
  
https://github.com/Zillaynain/autoware_mini_practice/blob/5a3fb5548f149fbd957bacad174efd37e01fe563/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L79-L92

**Comment by Zillaynain** [comment]
Please check

**Comment by geopimik** [comment]
2. OK
3. OK

1. Now when I look at the code then You have the same check in the code 2 times:
https://github.com/Zillaynain/autoware_mini_practice/blob/61f4952e2f9524fa720e1aa5c424721700755bab/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L40
and 
https://github.com/Zillaynain/autoware_mini_practice/blob/61f4952e2f9524fa720e1aa5c424721700755bab/practice_5/nodes/detection/lidar_cluster/cluster_detector.py#L64

Obviously you will never reach to second one. So it is redundant! Or maybe the first one is redundant because they check the same thing? But depending on where in the code the check is and what is inside the condition, the result can be very different. Anyway, this duplication should be removed.

**Comment by Zillaynain** [comment]
Please check.

**Comment by geopimik** [comment]
ok
