### ISSUE TITLE
Practice 6 and 7 - global planner

### ISSUE THREAD

**Issue by geopimik** [Zillaynain/autoware_mini_practice#9]
You should uncomment

https://github.com/Zillaynain/autoware_mini_practice/blob/5a3fb5548f149fbd957bacad174efd37e01fe563/practice_6/nodes/planning/global/lanelet2_global_planner.py#L92

otherwise in the console after reaching the goal point the following will be continuously printed out:
```
[WARN] [1718829993.275933]: the goal has been reached, path has been cleared. 
[INFO] [1718829993.276779]: /planning/simple_local_planner - Empty global path received
```

**Comment by geopimik** [comment]
Fix in both: in practice 6 and 7

**Comment by Zillaynain** [comment]
Please check

**Comment by geopimik** [comment]
ok
